defaults:
  - _self_
  - local_system  : ${oc.env:CMB_SIMS_LOCAL_SYSTEM}
  - file_system   : common_fs
  - pipeline      : assembly_petroff
  - scenario      : scenario_32
  # - splits        : "3-1"
  - splits        : all
  # simulation must listed be after scenario and splits to build the simulation seed
  - model/petroff : petroff_model
  - override hydra/job_logging: custom_log

dataset_name: ${scenario.map_fields}_${scenario.nside}_${splits.name}
working_dir : "Petroff_High_7/"
hydra:
  run:
    dir: Logs/${now:%Y-%m-%d-%H-%M-%S}
  verbose: false

# Settings below this point are used for interpolation.
# They are picked up from here and MAY be used elsewhere in the yamls.
# In the scenario yaml
nside     : 32
detectors : [70, 100, 143, 217, 353, 545, 857]
map_fields: "I"
