defaults:
  - _self_
  - local_system              : ${oc.env:CMB_ML_LOCAL_SYSTEM}
  - file_system               : common_fs
  - pipeline                  : assembly_pyilc
  - scenario                  : scenario_t
  - splits                    : all_t
  - model/pyilc               : hilc_t
  # - model/pyilc               : cnilc_512_t
  - model/analysis            : basic_analysis
  - override hydra/job_logging: custom_log

# dataset_name   : IQU_${scenario.nside}_1450
dataset_name   : ${scenario.map_fields}_${scenario.nside}_${splits.name}
working_dir    : "PyILC_HILC_Test/"
fig_model_name : HILC
# working_dir    : "PyILC_CNILC/"
# fig_model_name : CNILC
hydra:
  run:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}
  verbose      : true

# Settings below this point are used for interpolation.
# These are not to be used directly in python.
# They are picked up from here and MAY be used elsewhere in the yamls. Be careful, check assumptions!
# In the scenario yaml
# nside          : 512
nside          : 128
detectors      : [44, 70, 100, 143, 217, 353, 545, 857]
# detectors      : [44, 70, 100, 143, 217, 353]  # For HILC, 857 causes crashes when used with other detectors. Removing 30 and 857 was not enough to guarantee successful runs.
map_fields     : "I"

# In the pipeline yamls
# No epochs exist for PyILC method; use a placeholder:
use_epochs           : &epochs [""]
use_epochs_imgs      : *epochs
use_epochs_map_stats : *epochs
use_epochs_ps_stats  : *epochs
# Limit the number of simulations for which to generate figures
n_show_cap           : 1   # int: first n_sims; null: all sims; list: particular sims by index

# In the splits yaml; null to run on all
n_test_cap           : null

# In the model yaml, for HILC:
# ELLMAX: 511   # For 128
# ELLMAX: 2047  # For 512

# In the model yaml, for CNILC:
ELLMAX: 1534  # For 512
