defaults:
  - local_system: ${oc.env:CMB_SIMS_LOCAL_SYSTEM}
  - file_system : common_fs
  - simulation  : sim
  - scenario    : scenario
  - splits      : all
  - pipeline    : sample_pipe
  - override hydra/job_logging: custom_log
  - _self_

dataset_name: T_128_2450
seed_base_string: 'T-128-2450'
hydra:
  run:
    dir: Logs/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: Logs_multirun/${now:%Y-%m-%d-%H-%M-%S}
  verbose: 
  
nside_sky: 256
nside: 128
# These two could probably be overrides since they're only different for one
map_fields: "I"
detector_freqs: [30, 44, 70, 100, 143, 217, 353, 545, 857]