defaults:
  - _self_
  - local_system  : ${oc.env:CMB_SIMS_LOCAL_SYSTEM}
  - file_system   : common_fs
  - pipeline      : assembly_petroff
  - scenario      : scenario_t
  - splits        : all_t
  - model/petroff : petroff_model
  - override hydra/job_logging: custom_log

dataset_name: ${scenario.map_fields}_${scenario.nside}_${splits.name}
working_dir : "Petroff_reorder/"
hydra:
  run:
    dir: Logs/${now:%Y-%m-%d-%H-%M-%S}
  verbose: false


# Settings below this point are used for interpolation.
# These are not to be used directly in the python
# They are picked up from here and MAY be used elsewhere in the yamls.
# In the scenario yaml
# nside          : 128
nside          : 32
detectors      : [30, 44, 70, 100, 143, 217, 353, 545, 857]
# detectors      : [30, 44, 70, 100, 143, 217, 353]
# detectors      : [70, 100, 143, 217, 353, 545, 857]
map_fields     : "I"

# In the simulation yaml (only relevant to the simulation portion of the pipeline)
nside_sky      : 256
preset_strings : ["d9", "s4", "f1", "a1", "co1", "cib1", "ksz1", "tsz1", "rg1"]

# In the pipeline yamls
# use_epochs     : [10]
# use_epochs     : ["init", 1, 2, 5, 10, 40, 100]
# For prediction, postprocessing, power spectra generation:
use_epochs     : ["init", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# use_epochs     : ["init", 1]
# For single simulation figures (maps & ps figures):
use_epochs_imgs  : ["init", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  #, 12, 20, 30, 40]
# use_epochs_imgs  : ["init", 1]
# For summary statistics:
# use_epochs_stats : ["init", 1, 2, 5, 10, 20, 40]
use_epochs_stats : ["init", 1]
# Limit the number of simulations for which to generate figures
n_show_cap       : 1

# In the splits yaml; null to run on all
n_test_cap     : 1

# In the model yaml
n_epochs       : 10
restart_epoch  : null
batch          : 8
scale_method   : minmax
initialization : kaiming
learning_rate  : 0.001