defaults:
  - _self_
  - local_system : ${oc.env:CMB_SIMS_LOCAL_SYSTEM}
  - file_system  : common_fs
  - pipeline     : assembly_pyilc
  - scenario     : scenario_t
  - splits       : all_t
  - model/pyilc  : hilc_t
  - model/analysis: basic_analysis
  - override hydra/job_logging: custom_log

# dataset_name: ${scenario.map_fields}_${scenario.nside}_${splits.name}
dataset_name: IQU_${scenario.nside}_1450
working_dir : "PyILC_dev/"
seed_base_string: 'cmml'
hydra:
  run:
    dir: Logs/${now:%Y-%m-%d-%H-%M-%S}
  verbose: true


# Settings below this point are used for interpolation.
# These are not to be used directly in python.
# They are picked up from here and MAY be used elsewhere in the yamls. Be careful, check assumptions!
# In the scenario yaml
nside          : 512
detectors      : [30, 44, 70, 100, 143, 217, 353, 545, 857]
# detectors      : [30, 44, 70, 100, 143, 217, 353]
# detectors      : [70, 100, 143, 217, 353, 545, 857]
map_fields     : "I"

# In the pipeline yamls
# For prediction, postprocessing, power spectra generation:
use_epochs       : [""]
# For single simulation figures (maps & ps figures):
use_epochs_imgs  : [""]
# For summary statistics:
use_epochs_stats : [""]
# Limit the number of simulations for which to generate figures
n_show_cap       : 1

# In the splits yaml; null to run on all
n_test_cap     : 1

# In the model yaml, for HILC:
# ELLMAX: 511   # For 128
ELLMAX: 2047  # For 512
# ELLMAX: 4095  # For 1024
# ELLMAX: 6000  # For 2048
