defaults:
  - local_system   : ${oc.env:CMB_SIMS_LOCAL_SYSTEM}
  - file_system    : common_fs
  - pipeline       : assembly_model_comp
  - scenario       : scenario_t
  - splits         : all_t
  # - model/cmbnncs  : cmbnncs_model
  - model/analysis : basic_analysis
  - override hydra/job_logging: custom_log
  - _self_

# dataset_name: CMML_Dataset
# When creating multiple datasets, using interpolation like this may be easier:
# dataset_name: IQU_${scenario.nside}_${splits.name}
dataset_name       : ${scenario.map_fields}_${scenario.nside}_${splits.name}
working_dir        : "placeholder_set_below/"
fig_model_name : CMBNNCS
hydra:
  run:
    dir: Logs/${now:%Y-%m-%d-%H-%M-%S}
  verbose: false

models_comp:
  - cmbnncs:
    model_name        : CMBNNCS
    working_directory : CMBNNCS_UNet8/
    epoch             : 120
  - pyilc:
    model_name        : CNILC
    working_directory : PyILC_CNILC/
    # No epochs for this model
    epoch             : ""
ps_baseline           : theory


# Settings below this point are used for interpolation.
# These are not to be used directly in the python
# They are picked up from here and MAY be used elsewhere in the yamls.
# In the scenario yaml
nside          : 512
# detectors      : [30, 44, 70, 100, 143, 217, 353] # , 545, 857]
map_fields     : "I"

# In the model yaml
num_epochs       : 120

# In the pipeline yamls
# For prediction, postprocessing, power spectra generation:
use_epochs       : &epochs ["init", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 25, 40, 60, 80, 100, 120]
# For single simulation figures (maps & ps figures):
use_epochs_imgs  : *epochs
# For summary statistics:
# use_epochs_map_stats : ["init", 1, 2, 6, 25, 40, 120]
use_epochs_map_stats : [120]
# For summary statistics:
use_epochs_ps_stats : [120]
# Limit the number of simulations for which to generate figures
n_show_cap       : 1

# Limit the number of simulations on which to do inference and postprocessing
# In the splits yaml; null to run on all
n_test_cap       : null
