defaults:
  - local_system  : ${oc.env:CMB_SIMS_LOCAL_SYSTEM}
  - file_system   : common_fs
  - pipeline      : assembly_petroff
  - scenario      : scenario_32
  - splits        : all
  # simulation must listed be after scenario and splits to build the simulation seed
  - model/petroff : petroff_model
  - override hydra/job_logging: custom_log
  - _self_

dataset_name: ${scenario.map_fields}_${scenario.nside}_${splits.name}
hydra:
  run:
    dir: Logs/${now:%Y-%m-%d-%H-%M-%S}
  verbose: true