defaults:
  - local_system: ${oc.env:CMB_SIMS_LOCAL_SYSTEM}
  - file_system : common_fs
  - simulation  : base_sim
  - override hydra/job_logging: custom_log_with_extra_seed
  - _self_

create_dirs       : false
create_noise_cache: false
dataset_name      : dummy_map_check
splits            : none
seed_base_string  : 'dummy_map_check'
