defaults:
  - local_system   : ${oc.env:CMB_SIMS_LOCAL_SYSTEM}
  - file_system    : common_fs
  - pipeline       : assembly_cmbnncs
  - scenario       : scenario_t
  - splits         : all_t
  # simulation must listed be after scenario and splits to build the simulation seed
  # - model/sim     : sim_trivial
  - model/cmbnncs  : cmbnncs_model
  - model/analysis : basic_analysis
  - override hydra/job_logging: custom_log
  - _self_

# dataset_name: CMML_Dataset
# When creating multiple datasets, using interpolation like this may be easier:
dataset_name: ${scenario.map_fields}_${scenario.nside}_${splits.name}
working_dir : "CMBNNCS/"
hydra:
  run:
    dir: Logs/${now:%Y-%m-%d-%H-%M-%S}
  verbose: false

# Settings below this point are used for interpolation.
# These are not to be used directly in the python
# They are picked up from here and MAY be used elsewhere in the yamls.
# In the scenario yaml
nside          : 128
# nside          : 32
detectors      : [100, 143, 217, 353]
# detectors      : [30, 44, 70, 100, 143, 217, 353, 545, 857]
# detectors      : [30, 44, 70, 100, 143, 217, 353]
# detectors      : [70, 100, 143, 217, 353, 545, 857]
map_fields     : "I"

# In the model yaml
num_epochs       : 40

# In the pipeline yamls
# For prediction, postprocessing, power spectra generation:
use_epochs       : ["init", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 20, 30, 40]
# use_epochs     : [10]
# use_epochs     : ["init", 1, 2, 5, 10, 40, 100]
# For single simulation figures (maps & ps figures):
use_epochs_imgs  : ["init", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 20, 30, 40]
# For summary statistics:
use_epochs_stats : ["init", 1, 2, 5, 10, 20, 40]
# Limit the number of simulations for which to generate figures
n_show_cap       : 1

# Limit the number of simulations on which to do inference and postprocessing
# In the splits yaml; null to run on all
n_test_cap       : null