defaults:
  - local_system: jim_laptop
  - file_system : common_fs
  - simulation  : base_sim
  - override hydra/job_logging: custom_log
  - _self_

splits: none
create_dirs: false
dataset_name: dummy
