test3:
  _target_: pysm3.ModifiedBlackBody
  map_I: /home/adam/cmb_project/Assets/ComponentMaps/d9.fits
  map_mbb_index: 1.99
  map_mbb_temperature: 50
  unit_mbb_temperature: K
  freq_ref_I: 353 GHz
  freq_ref_P: 353 GHz
  max_nside: 8192
  nside: ${model.sim.nside_sky}