test5:
  _target_: pysm3.PowerLaw
  map_I: /home/adam/cmb_project/Assets/ComponentMaps/f1.fits
  unit_I: uK_RJ
  map_pl_index: -2.14
  freq_ref_I: 30 GHz
  has_polarization: false
  nside: ${model.sim.nside_sky}