from .stage_executors.B_extrema_make_serial import SerialPreprocessMakeExtremaExecutor
from .stage_executors.B_extrema_make import PreprocessMakeExtremaExecutor
from .stage_executors.C_check_transforms import CheckTransformsExecutor
from .stage_executors.D_train import TrainingExecutor
from .stage_executors.E_predict import PredictionExecutor
from .stage_executors.F_postprocess import PostprocessExecutor

# from .dummymodel import DummyNeuralNetwork