defaults:
  - local_system   : generic_lab
  - file_system    : common_fs
  - pipeline       : assembly_sim_flex
  - scenario       : scenario
  - splits         : all
  - model/sim      : sim_flex_fgs
  - model/analysis : basic_analysis
  - override hydra/job_logging: custom_log
  - _self_

dataset_name: "${map_fields}_${scenario.nside}_${splits.name}_PLACEHOLDER"
working_dir : "Simulation_Working/"
hydra:
  run:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}  # Should be the same as run.dir
    subdir     : ${hydra.job.num}               # Subsequent jobs will include duplicate logs for all previous jobs. 
                                                #   This is a minor bug, not worth fixing.
  verbose      : false

# Settings below this point are used for interpolation.
# These are not to be used directly in the python
# They are picked up from here and MAY be used elsewhere in the yamls.
# In the scenario yaml
nside          : 512
detectors      : [100, 143, 217, 353]
map_fields     : "I"

# In the simulation yaml (only relevant to the simulation portion of the pipeline)
# nside_sky      : 2048  # Removed interpolation; this should be in the sim config, not here.
min_obs_beam   :  0  # When running with nside_out==512
# min_obs_beam   :  82.5  # When running with nside_out==128
