cmb:
  _target_: pysm3.CMBLensed # do I still want to use this?
  cmb_spectra: cmb_spectrum.txt # something else?
  nside: ${nside_sky} # is this the right one?
  cmb_seed: 0 # does this need a better way to be set?